name: Deploy Vite App to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Use your Vite app's Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build Vite app
      run: npm run build

    - name: Verify dist directory
      run: ls -al ./dist

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Add EC2 host to known_hosts
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

        scp -r ./dist $USER@$HOST:/var/www/react-app
        ssh $USER@$HOST "sudo systemctl restart nginx"
